# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 10:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0, verbose_name='Amount')),
                ('successful', models.BooleanField(default=False, verbose_name='Successful')),
                ('transaction_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='Transaction Code')),
                ('tref', models.CharField(blank=True, max_length=255, null=True, verbose_name='Bank Tref')),
                ('log_text', models.TextField(default='', help_text='Some logs as simple text, showing payment status.', verbose_name='Log Text')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_records', to=settings.AUTH_USER_MODEL, verbose_name='Payer')),
            ],
            options={
                'verbose_name_plural': 'Payment Records',
                'verbose_name': 'Payment Record',
            },
        ),
    ]
